apiVersion: v1
kind: Pod
metadata:
    name: my-ip-app
spec:
    containers:
       - name: ip-app
         image: pradippawar313/ip_app:latest
         ports:
            - containerPort: 80
         volumeMounts:
         - name: my-volume
           mountPath: '/app/volume'
    volumes:
    - name: my-volume 
      persistentVolumeClaim:
          claimName: my-pvc