
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ip_app-deployment
spec:
    replicas: 4
    template:
        metadata:
            labels:
                app: ip_app
        spec:
            containers:
                - name: ipapp
                  image: pradippawar313/ip_app:latest
                  ports:
                    - containerPort: 80
    selector: 
        matchLabels:
            app: ip_app

---

apiVersion: apps/v1
kind: Service
metadata:
    name: ip_app-cluster-ip
spec:
    type: ClusterIP
    selector:
        app: ip_app
    ports:
        - name: http
          port: 30002
          targetPort: 80

