apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx2
spec:
    replicas: 4
    template:
        metadata:
            labels:
                app: my-nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:1.23
                  ports:
                    - containerPort: 80
    selector: 
        matchLabels:
            app: my-nginx