apiVersion: apps/v1
kind: Deployment
metadata:
    name: python-deployment
spec:
    replicas: 4
    template:
        metadata:
            labels:
                app: python
        spec:
            containers:
                - name: ipapp
                  image: pradippawar313/python:v1
                  ports:
                    - containerPort: 80
    selector: 
        matchLabels:
            app: python

---
apiVersion: apps/v1
kind: Service
metadata:
    name: python-cluster-ip
spec:
    type: ClusterIP
    selector:
        app: python
    ports:
        - name: http
          port: 30002
          targetPort: 80
