apiVersion: v1
kind: Pod
metadata:
    name: my-ip-app
spec:
    containers:
       - name: ip-app
         image: pradippawar313/ip_app:latest
         ports:
            - containerPort: 80
         env:
         - name: DB_URL
           valueFrom:
              secretMapKeyRef:
                name: my-secret
                key: db_url
         - name: DB_UNAME
           valueFrom:
              secretMapKeyRef:
                name: my-secret
                key: db_username
         - name: DB_PASS
           valueFrom:
              secretMapKeyRef:
                name: my-secret
                key: db_password
                
            




